apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  type: {{.Values.service.type}}
  ports:
  {{- toYaml .Values.service.ports | nindent 4 }}
